version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

